/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {

    public static int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };

    public static void main(String[] args) {
        boolean duplicates = duplicates(roll(1));
        int[] testArrTrue02 = {7, 20, 8, -22};
        float testfloat = averageCalculator(testArrTrue02);
        float testfloat2 = lowestAverage(weeklyMonthTemperatures);
    }
    public static int[] roll (int n){
        Random rand = new Random();
        int[] rolls = new int[n];

        for (int i = 0; i < n; i++) {
            int thisRoll = rand.nextInt(6);
            rolls[i] = thisRoll + 1;
        }

        return rolls;
    }

    public static boolean duplicates (int[] arr){
        int testNum;

        for (int i = 0; i < arr.length; i++) {
            testNum = arr[i];
            for (int j = 0; j < arr.length; j++) {
                if(j != i){
                    if(arr[j] == testNum){
                        return true;
                    }
                }
            }
        }

        return false;
    }

    public static float averageCalculator(int[] arr){
        float total = 0;

        for (int i: arr) {
            total += i;
        }

        return total /= arr.length;
    }



    public static float lowestAverage (int[][] arrs){
        float lowestAvg = averageCalculator(arrs[0]);

        for (int i = 1; i < arrs.length; i++) {
            float tempAvg = averageCalculator(arrs[i]);
            if( tempAvg < lowestAvg){
                lowestAvg = tempAvg;
            }
        }

        return lowestAvg;
    }
}
