/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {
    public static int[] roll (int n){
        Random rand = new Random();
        int[] rolls = new int[n];

        for (int i = 0; i < n; i++) {
            int thisRoll = rand.nextInt(6);
            rolls[i] = thisRoll + 1;
        }
        return rolls;
    }

    public static boolean duplicates (int[] arr){
        int testNum;

        for (int i = 0; i < arr.length; i++) {
            testNum = arr[i];
            for (int j = 0; j < arr.length; j++) {
                if(j != i){
                    if(arr[j] == testNum){
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static float averageCalculator(int[] arr){
        float total = 0;

        for (int i: arr) {
            total += i;
        }
        return total /= arr.length;
    }

    public static float lowestAverage (int[][] arrs){
        float lowestAvg = averageCalculator(arrs[0]);

        for (int i = 1; i < arrs.length; i++) {
            float tempAvg = averageCalculator(arrs[i]);
            if( tempAvg < lowestAvg){
                lowestAvg = tempAvg;
            }
        }
        return lowestAvg;
    }
}
