/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.checkerframework.common.returnsreceiver.qual.This;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {
    String testString;

    @Test void testRestaurantToString(){
        Restaurant cut = new Restaurant("Turbo Fries", "fast food");

        testString = "Turbo Fries is a fast food restaurant. This restaurant has a star average of 0.0 stars.";

        assertTrue(testString.equals(cut.toString()));
    }

    @Test void testReviewToString(){
        Review cut = new Review("Dan", "S'ok, kinda gross though.", 1.2f);

        testString = "Dan gave this restaurant 1.2 stars and left the following review: S'ok, kinda gross though.";

        assertTrue(testString.equals(cut.toString()));
    }

    @Test void testAddReview(){

        Review cut = new Review("Dan", "S'ok, kinda gross though.", 1.2f);
        Restaurant testRestaurant = new Restaurant("Turbo Fries", "fast food");
        testRestaurant.addReview(cut);

        testString = "[Dan gave this restaurant 1.2 stars and left the following review: S'ok, kinda gross though.]";
        assertTrue(testString.equals(testRestaurant.getReviews().toString()));
        assertTrue(testRestaurant.getStarAverage() == 1.2f);

        cut = new Review("Doofy", "I mean, it's alright.", 2.8f);
        testRestaurant.addReview(cut);

        assertTrue(testRestaurant.getStarAverage() == 2f);

        cut = new Review("Stanky", "The bomb dot come! Come get some.", 5.0f);
        testRestaurant.addReview(cut);

        assertTrue(testRestaurant.getStarAverage() == 3f);
    }
}
